# CS171-EE142 - Fall 2023 - Homework 1

# Due: Wednesday, October 11, 2023 @ 11:59pm

### Maximum points: 25 pts


## Submit your solution to Gradescope:
1. Submit a single PDF to **HW1**
2. Submit your jupyter notebook to **HW1-code**

**See the additional submission instructions at the end of this notebook**


## Enter your information below:

### Your Name (submitter): Siddharta Dutta

### Your student ID (submitter): 862292896
    
    
<b>By submitting this notebook, I assert that the work below is my own work, completed for this course.  Except where explicitly cited, none of the portions of this notebook are duplicated from anyone else's work or my own previous work.</b>


## Academic Integrity
Each assignment should be done  individually. You may discuss general approaches with other students in the class, and ask questions to the TAs, but  you must only submit work that is yours . If you receive help by any external sources (other than the TA and the instructor), you must properly credit those sources, and if the help is significant, the appropriate grade reduction will be applied. If you fail to do so, the instructor and the TAs are obligated to take the appropriate actions outlined at http://conduct.ucr.edu/policies/academicintegrity.html . Please read carefully the UCR academic integrity policies included in the link.


# Overview
In this assignment you will refreash basic linear algebra like multiplication rules and norms.

Please **do not use pre-defined functions** to solve the questions unless we specify them in the question descriptions. For example, **do not use `numpy.linalg.norm` to solve question 2 in this homework**, instead, you should understand the definition of the norm and be able to implement it with the basic operations.


## Read *all* cells carefully and answer all parts


# Basic NumPy

NumPy is a powerful numerical computing Python package.
Below we will summarize some basic linear algebra operations you will need to complete this assignment.

Before using `NumPy`, we need to import it at the very beggining of the script with:

In [1]:
import numpy as np
import math

To create a vector/matrix, use `np.array()` that takes a python `list` as input and returns a vector/matrix variable that contains the same elements as in the `list`. Here are some examples on how to create vectors/matrices using `np.array`.

In [ ]:
# To create an vector:
vector = [1,2,3]
vector = np.array(vector)
# or
vector = np.array([1,2,3])
print(f'Created vector: {vector}\n')

# To create an 3x4 matrix:
matrix = [[1,2,3, 4],[5,6,7,8],[9,10,11,12]]
matrix = np.array(matrix)
# or
matrix = np.array([[1,2,3, 4],[5,6,7,8],[9,10,11,12]])
print(f'Created matrix:\n{matrix}')

Created vector: [1 2 3]

Created matrix:
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


To check the shape of `np.array` variables you created, use attribute `.shape`, so that you know you create the right vector/matrix you want.

In [ ]:
print(f'Shape of vector: {vector.shape}')
print(f'Shape of matrix: {matrix.shape}')

Shape of vector: (3,)
Shape of matrix: (3, 4)


To obtain the transpose of `np.array`, use attribute `.T`.

In [ ]:
print(f'Transposed matrix:\n{matrix.T}')

Transposed matrix:
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


To compute element-wise product between two matrices, use `*`. <br>
To compute matrix multiplication between two matrices, use `@`.

In [ ]:
print(f'Element-wise product:\n{matrix * matrix}')
print(f'Matrix product:\n{matrix @ matrix.T}')

Element-wise product:
[[  1   4   9  16]
 [ 25  36  49  64]
 [ 81 100 121 144]]
Matrix product:
[[ 30  70 110]
 [ 70 174 278]
 [110 278 446]]


To sum all the element of a vector, call `.sum()`

In [ ]:
print(f'Summation of vector elements: {vector.sum()}')

Summation of vector elements: 6


For a matrix, we can perform summation along different dimensions using `axis` parameter. \
For example, summation along `axis=0` will give a row vector that is the sum of all the rows. In other words, first entry will be the summation of entries in the first column, second entry will be the summation of entries in the second column, and so on.

In [ ]:
print(f'Summation of all the rows: {matrix.sum(axis=0)}')
print(f'Summation of all the columns: {matrix.sum(axis=1)}')
print(f'Summation of all the elements: {matrix.sum()}')

Summation of matrix rows: [15 18 21 24]
Summation of matrix columns: [10 26 42]
Summation of matrix elements: 78


For more information on using NumPy, please refer to the [official documentation](https://numpy.org/doc/stable/). <br>
Enjoy!

# Basic linear algebra [25 pts]

## Question 1. Vector-matrix arithmetic [13 pts]

#### 1.1. Element-wise product [2 pts]  
The elementwise product of two matrices is called the Hadamard product and denoted as $\odot$ (called `odot` notation). Suppose we are given two $m\times n$ matrices as
$$
\mathbf{A} =
\begin{bmatrix}
a_{11} & a_{12} & \dots & a_{1n} \\
a_{21} & a_{22} & \dots & a_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1} & a_{m2} & \dots & a_{mn} \\
\end{bmatrix},\
\mathbf{B} =
\begin{bmatrix}
b_{11} & b_{12} & \dots & b_{1n} \\
b_{21} & b_{22} & \dots & b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
b_{m1} & b_{m2} & \dots & b_{mn} \\
\end{bmatrix}
$$

We can compute the Hadamard product of $\mathbf{A},\mathbf{B}$ as
$$
\mathbf{A} \odot \mathbf{B} =
\begin{bmatrix}
a_{11}b_{11} & a_{12}b_{12} & \dots & a_{1n}b_{1n} \\
a_{21}b_{21} & a_{22}b_{22} & \dots & a_{2n}b_{2n} \\
\vdots & \vdots & \ddots & \vdots \\
a_{m1}b_{m1} & a_{m2}b_{m2} & \dots & a_{mn}b_{mn} \\
\end{bmatrix}
$$

Create two matrices using `numpy.array` as
$\mathbf{A} = \begin{bmatrix}
5 & 0 & 7 \\
6 & 1 & 3 \\
5 & 9 & 3 \\
\end{bmatrix}$
and
$\mathbf{B} = \begin{bmatrix}
1 & 0 & 2 \\
0 & 2 & 1 \\
1 & 1 & 2 \\
\end{bmatrix}$
and compute $\mathbf{A} \odot \mathbf{B}$.


In [3]:
# TODO: complete the code blocks below
# Hint: to quickly comment/uncomment, select line(s) and press 'ctrl' + '/'.

A = np.array([[5,0,7],[6,1,3],[5,9,3]])
B = np.array([[1,0,2],[0,1,1],[1,1,2]])

hadamard_product = A * B
print(f'Hadamard product of A and B: {hadamard_product}')

Hadamard product of A and B: [[ 5  0 14]
 [ 0  1  3]
 [ 5  9  6]]



#### 1.2. Scalar or dot product [2 pts]  

Scalar, dot, or inner product of two vectors $\mathbf{x},\mathbf{y}\in\mathbb{R}^d$ can be defined as the summation of the element-wise product of all the entries in two vectors:

$$\mathbf{x}^\top\mathbf{y} = \langle\mathbf{x}, \mathbf{y}\rangle =  \sum_{i=1}^dx_iy_i.$$

Now, create two length of 3 vectors **using any six digits from your student ID**.

For instance, $\mathbf{x} = \begin{bmatrix}6 \\ 1 \\ 9\end{bmatrix}$ and $\mathbf{y} = \begin{bmatrix}4 \\ 3 \\ 8\end{bmatrix}$, and then compute $\mathbf{x}^\top\mathbf{y}$.


In [4]:
# TODO: complete the code blocks below
x = np.array([[8],[6],[2]])
y = np.array([[2],[9],[2]])

inner_product = (x * y).sum()
print(f'Inner product of x and y: {inner_product}')

Inner product of x and y: 74


#### 1.3. Matrix–vector products [3 pts] <br>
Now that we know how to calculate dot products, we can begin to understand the product between an matrix $\mathbf{A}$ and an $n$-dimensional vector $\mathbf{x}$. To start off, we view our matrix in terms of its row vectors:
$$
\mathbf{A} =
\begin{bmatrix}
\mathbf{a}_{1}^\top\\
\mathbf{a}_{2}^\top\\
\vdots\\
\mathbf{a}_{m}^\top\\
\end{bmatrix},
$$<br>
where each $\mathbf{a}_{i}^\top\in\mathbb{R}^n$ is a row vector representing the $i^{\textrm{th}}$ row of the matrix $\mathbf{A}$.<br>
The matrix–vector product $\mathbf{Ax}$ is simply a column vector of length $m$, whose $i^{\textrm{th}}$ element is the dot product $\mathbf{a}_{i}^\top\mathbf{x}$:
$$
\mathbf{Ax} =
\begin{bmatrix}
\mathbf{a}_{1}^\top\mathbf{x}\\
\mathbf{a}_{2}^\top\mathbf{x}\\
\vdots\\
\mathbf{a}_{m}^\top\mathbf{x}\\
\end{bmatrix}.
$$<br>

Compute the $\mathbf{Ax}$ using values of $\mathbf{A}$ and $\mathbf{x}$ in 1.1 and 1.2.

In [11]:
def dotProd(m1, m2):
    # get dimensions
    newMR = np.shape(m1)[0]     #3
    newMC = np.shape(m2)[1]     #1

    # make empty matrix
    newM = np.empty([newMR, newMC])
    
    # based on rows, multipy + add
    for np.shape(m1)[0]

    pass

dotProd(A, x)

3


In [13]:
# TODO: complete the code blocks below
# Hint: you can use matrix-vector product in numpy using one operation

mat_vec_product = A @ x

print(f'Product of A and x: {mat_vec_product}')

Product of A and x: [[93]
 [64]
 [66]]


#### 1.4. Matrix–matrix multiplication [3 pts] <br>
Suppose we have two matrix $\mathbf{A}$ and $\mathbf{B}$ that can be viewed as "vector of vectors", the same described as question 3:
$$
\mathbf{A} =
\begin{bmatrix}
\mathbf{a}_{1}^\top\\
\mathbf{a}_{2}^\top\\
\vdots\\
\mathbf{a}_{m}^\top\\
\end{bmatrix},\quad
\mathbf{B} =
\begin{bmatrix}
\mathbf{b}_{1} & \mathbf{b}_{2} & \cdots & \mathbf{b}_{n}
\end{bmatrix}.
$$<br>
To compute the matrix product $\mathbf{C}\in\mathbb{R}^{m\times n}$, we simply compute each element $c_{ij}$ as the dot product between the $i^{\textrm{th}}$ row of $\mathbf{A}$ and the $j^{\textrm{th}}$ column of $\mathbf{B}$, $\textrm{i.e.},\mathbf{a}_{i}^\top\mathbf{b}_{j}$:
$$
\mathbf{AB} =
\begin{bmatrix}
\mathbf{a}_{1}^\top\mathbf{b}_{1} & \mathbf{a}_{1}^\top\mathbf{b}_{2} & \dots & \mathbf{a}_{1}^\top\mathbf{b}_{n}\\
\mathbf{a}_{2}^\top\mathbf{b}_{1} & \mathbf{a}_{2}^\top\mathbf{b}_{2} & \dots & \mathbf{a}_{2}^\top\mathbf{b}_{n}\\
\vdots & \vdots & \ddots & \vdots\\
\mathbf{a}_{m}^\top\mathbf{b}_{1} & \mathbf{a}_{m}^\top\mathbf{b}_{2} & \dots & \mathbf{a}_{m}^\top\mathbf{b}_{n}\\
\end{bmatrix}.
$$<br>

Compute the $\mathbf{AB}$ with values given in 1.1, that is $\mathbf{A} = \begin{bmatrix}
5 & 0 & 7 \\
6 & 1 & 3 \\
5 & 9 & 3 \\
\end{bmatrix}$
and
$\mathbf{B} = \begin{bmatrix}
1 & 0 & 2 \\
0 & 2 & 1 \\
1 & 1 & 2 \\
\end{bmatrix}$.

In [15]:
# TODO: complete the code blocks below
A = np.array([[5,0,7],[6,1,3],[5,9,3]])
B = np.array([[1,0,2],[0,2,1],[1,1,2]])

mat_product = A @ B
print(f'Product of A and B: {mat_product}')

Product of A and B: [[12  7 24]
 [ 9  5 19]
 [ 8 21 25]]


#### 1.5. Hadamard and dot product validity [3 pts]

Suppose we are given two vectors
$$x = \begin{bmatrix} 1 \\ 3 \\ 5\end{bmatrix},\ y =  \begin{bmatrix} 2 \\ 4\\ 6 \\ 8 \end{bmatrix}$$


1. Can you compute the Hadamard product as $x\odot y$? Why?

    A. No because Hadamard products require matrices of the same size; both should be of dimensions m x n.
2. Can you compute the dot/inner product as $x^\top y$? Why?

    A. No because dot/inner products are summations of Hadamard products and we cannot compute the Hadamard product.
3. Can you compute matrix product as $xy^\top$? Why?

    A. No because to compute matrix products the number of columns of the first matrix must match the number of rows in the second matrix.

## Question 2. Norm, distance and similarity [12 pts]

#### 2.1. Norm of vector [6 pts]  


<!-- ![norm](https://miro.medium.com/v2/resize:fit:480/1*ZreluxyiXJnjWNcEZ_HHSQ.png) -->

The $\ell_1$ norm is also common and the associated measure is called the Manhattan distance. By definition, the $\ell_1$ norm sums the absolute values of a vector’s elements:
$$
\|\mathbf{x}\|_1 = \sum_{i=1}^n|x_i|,
$$
The $\ell_2$ norm is also common and the associated measure is called the Euclidean distance. By definition, the $\ell_2$ norm is the square root of summation of the square values of a vector’s elements:
$$
\|\mathbf{x}\|_2 = \sqrt{\sum_{i=1}^n x_i^2},
$$
Both $\ell_1$ and $\ell_2$ norms can be represented in the more general $\ell_p$ norms:
$$
\|\mathbf{x}\|_p = \left(\sum_{i=1}^n|x_i|^p\right)^{1/p},
$$


Now, create two length of 3 vectors **using any six digits from your student ID** (feel free to use the same vecotrs from the previous question).

For instance, $\mathbf{x} = \begin{bmatrix}6 \\ 1 \\ 9\end{bmatrix}$ and $\mathbf{y} = \begin{bmatrix}4 \\ 3 \\ 8\end{bmatrix}$, and then compute the $\ell_1$ and $\ell_2$ norms of vectors $\mathbf{x}$ and $\mathbf{y}$.


(* Please **do not use pre-defined functions** to solve the question, in this question you cannot use `numpy.linalg.norm` to skip the job)

In [8]:
# TODO: complete the code blocks below

l1_x = np.sum(np.absolute(x))
l2_x = np.sqrt(l1_x)
print(f'l1 norm of x: {l1_x}, l2 norm of x: {l2_x}')

l1_y = np.sum(np.absolute(y))
l2_y = np.sqrt(l1_y)
print(f'l1 norm of y: {l1_y}, l2 norm of y: {l2_y}')

l1 norm of x: 16, l2 norm of x: 4.0
l1 norm of y: 13, l2 norm of y: 3.605551275463989


#### 2.2. Distance [3 pts]  


The $\ell_p$ distance between two vectors $\mathbf{x}_i, \mathbf{x}_j \in \mathbb{R}^n$ can be written as  
$$\|\mathbf{x}_i - \mathbf{x}_j\|_p = \left(\sum_{k=1}^n |\mathbf{x}_i(k) - \mathbf{x}_j(k)|^p\right)^{1/p}, $$
which is the $\ell_p$ norm of vector $\mathbf{x}_i- \mathbf{x}_j$.


Now, create two length of 3 vectors **using any six digits from your student ID** (feel free to use the same vecotrs from the previous question).


For instance, $\mathbf{x} = \begin{bmatrix}6 \\ 1 \\ 9\end{bmatrix}$ and $\mathbf{y} = \begin{bmatrix}4 \\ 3 \\ 8\end{bmatrix}$, and then compute the $\ell_1$ and $\ell_2$ distance between vectors $\mathbf{x}$ and $\mathbf{y}$.

In [9]:
# TODO: complete the code blocks below

l1_xy = np.sum(np.absolute(np.subtract(x,y)))
l2_xy = np.sqrt(l1_xy)
print(f'l1 distance between x y: {l1_xy}')
print(f'l2 distance between x y: {l2_xy}')

l1 distance between x y: 9
l2 distance between x y: 3.0


#### 2.3. Similarity [3 pts]


To measures the similarity between two vectors of an inner product space, the commly used metric is the *cosine similarity*. The cosine similarity between two vectors $\mathbf{x}_i, \mathbf{x}_j \in \mathbb{R}^n$ define as:
$$
\mathrm{cos}\theta = \frac{\mathbf{x}_i^\top  \mathbf{x}_j}{\|\mathbf{x}_i\|_2 \|\mathbf{x}_j\|_2} =
\frac{\sum_{k=1}^n\mathbf{x}_i(k)\mathbf{x}_j(k)}{\sqrt{\sum_{k=1}^n\mathbf{x}_i(k)^2\cdot\sum_{i=1}^n\mathbf{x}_j(k)^2}}.
$$
In $2$-D case, the cosine similarity between two vectors is the cosine value of the angle formed by the vectors.


Now, create two length of 3 vectors **using any six digits from your student ID** (feel free to use the same vecotrs from the previous question).


For instance, $\mathbf{x} = \begin{bmatrix}6 \\ 1 \\ 9\end{bmatrix}$ and $\mathbf{y} = \begin{bmatrix}4 \\ 3 \\ 8\end{bmatrix}$, and then compute cosine similarity between vectors $\mathbf{x}$ and $\mathbf{y}$.

In [7]:
# TODO: complete the code blocks below

cos_xy = ((x * y).sum())/(l2_x * l2_y)
print(f'Cosine similarity between x y: {cos_xy}')

Cosine similarity between x y: 5.130976815083369


---
## Submission instructions
1. Download this Colab to ipynb, and convert it to PDF. Follow similar steps as [here](https://stackoverflow.com/questions/53460051/convert-ipynb-notebook-to-html-in-google-colab) but convert to PDF.
 - Download your .ipynb file. You can do it using only Google Colab. `File` -> `Download` -> `Download .ipynb`
 - Reupload it so Colab can see it. Click on the `Files` icon on the far left to expand the side bar. You can directly drag the downloaded .ipynb file to the area. Or click `Upload to session storage` icon and then select & upload your .ipynb file.
 - Conversion using %%shell.
 ```
!sudo apt-get update
!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic
!jupyter nbconvert --log-level CRITICAL --to pdf name_of_hw.ipynb
  ```
 - Your PDF file is ready. Click 3 dots and `Download`.


  

2. Upload the PDF to Gradescope, select the correct pdf pages for each question. **Important!**

3. Upload the ipynb file to Gradescope


Notice:
In case of errors in conversion, please check your LaTeX and debug. In Markdown, when you write in LaTeX math mode, do not leave any leading and trailing whitespaces inside the dollar signs ($). For example, write `(dollarSign)\mathbf(dollarSign)(dollarSign)` instead of `(dollarSign)(space)\mathbf{w}(dollarSign)`. Otherwise, nbconvert will throw an error and the generated pdf will be incomplete.

[This is a bug of nbconvert.](https://tex.stackexchange.com/questions/367176/jupyter-notebook-latex-conversion-fails-escaped-and-other-symbols)


In [ ]:
!sudo apt-get update
!sudo apt-get install texlive-xetex texlive-fonts-recommended texlive-plain-generic

In [ ]:
!jupyter nbconvert --log-level CRITICAL --to pdf fall2023_hw1.ipynb # make sure the ipynb name is correct